development:
  adapter: postgresql
  encoding: unicode
  database: mastermind_development
  pool: 5
  username: mastermind
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: mastermind_test
  pool: 5
  username: mastermind
  password:

cucumber:
  <<: *test